pipelines:
  Cal-build:
    group: calgroup
    materials:
      Mygit:
       git: https://github.com/laxmi82/Calulator_Terraform.git
    stages:
      - build:
          jobs:
           buildtask:
                tasks:
                 - exec:
                     command: mvn clean package    
